# Generated by Django 4.0.5 on 2022-06-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portugues',
            name='link',
        ),
        migrations.RemoveField(
            model_name='portugues',
            name='topico',
        ),
        migrations.AddField(
            model_name='portugues',
            name='resumo',
            field=models.TextField(default=True),
        ),
    ]
