# Generated by Django 4.0.5 on 2022-06-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_portugues_link_remove_portugues_topico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portugues',
            name='topico',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
