# Generated by Django 4.0.5 on 2022-06-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_portugues_topico'),
    ]

    operations = [
        migrations.AddField(
            model_name='portugues',
            name='link',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
