# Generated by Django 4.0.5 on 2022-06-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_portugues_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portugues',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portugues',
            name='topico',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
