# Generated by Django 4.0.5 on 2022-06-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_portugues_link_alter_portugues_topico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portugues',
            old_name='link',
            new_name='link_arquivo1',
        ),
        migrations.RenameField(
            model_name='portugues',
            old_name='topico',
            new_name='link_arquivo2',
        ),
        migrations.AddField(
            model_name='portugues',
            name='link_arquivo3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portugues',
            name='tipo_arquivo1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portugues',
            name='tipo_arquivo2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portugues',
            name='tipo_arquivo3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
