# Generated by Django 4.0.5 on 2022-06-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_link_portugues_link_arquivo1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portugues',
            old_name='resumo',
            new_name='p1',
        ),
        migrations.AddField(
            model_name='portugues',
            name='p2',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='portugues',
            name='p3',
            field=models.TextField(default=True),
        ),
    ]
