# Generated by Django 4.0.5 on 2022-06-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_portugues_link_arquivo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portugues',
            name='link_arquivo1',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='portugues',
            name='link_arquivo2',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='portugues',
            name='link_arquivo3',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
