# Generated by Django 4.0.5 on 2022-06-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_portugues_tipo_arquivo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portugues',
            name='link_arquivo2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portugues',
            name='tipo_arquivo2',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
